POST https://node-do-zero-xzz3.onrender.com/videos
Content-Type: application/json

{
    "title": "Leticia eu te amo",
    "description":"Teste",
    "duration": 180
}

###
GET https://node-do-zero-xzz3.onrender.com/videos
###
PUT https://node-do-zero-xzz3.onrender.com/videos/f9a99597-a523-4f92-b663-e918e4118556
Content-Type: application/json

{
    "title": "Leticia amor",
    "description":"Esse é o primeiro vídeo.",
    "duration": 180
}

###

DELETE https://node-do-zero-xzz3.onrender.com/videos/a83cf965-c4ac-40e7-a60d-b82e0d9522ee

